on:
  push:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        
        - name: set up python env
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'
            cache: 'pip' # caching pip dependencies

        - name: install dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: format code
          run: black .

        - name: lint code
          run: flake8 .

        - name: run tests
          run: pytest

        